<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>pb.FileRelocatedResponse</code>
 */
class FileRelocatedResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.pb.StatusCode status = 1;</code>
     */
    private $status = 0;

    public function __construct() {
        \GPBMetadata\File::initOnce();
        parent::__construct();
    }

    /**
     * <code>.pb.StatusCode status = 1;</code>
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * <code>.pb.StatusCode status = 1;</code>
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Pb\StatusCode::class);
        $this->status = $var;
    }

}

