<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Pb;

/**
 * Protobuf type <code>pb.FileType</code>
 */
class FileType
{
    /**
     * Generated from protobuf enum <code>All = 0;</code>
     */
    const All = 0;
    /**
     * Generated from protobuf enum <code>Recording_mp4 = 1;</code>
     */
    const Recording_mp4 = 1;
    /**
     * Generated from protobuf enum <code>Recording_hls = 6;</code>
     */
    const Recording_hls = 6;
    /**
     * Generated from protobuf enum <code>Wordpress_collage = 2;</code>
     */
    const Wordpress_collage = 2;
    /**
     * Generated from protobuf enum <code>Infinity_collage = 3;</code>
     */
    const Infinity_collage = 3;
    /**
     * Generated from protobuf enum <code>Infinity_sprite = 4;</code>
     */
    const Infinity_sprite = 4;
    /**
     * Generated from protobuf enum <code>Infinity_image = 5;</code>
     */
    const Infinity_image = 5;
}

