<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: struct.proto

namespace Pb;

/**
 * `NullValue` is a singleton enumeration to represent the null value for the
 * `Value` type union.
 *  The JSON representation for `NullValue` is JSON `null`.
 *
 * Protobuf type <code>pb.NullValue</code>
 */
class NullValue
{
    /**
     * Null value.
     *
     * Generated from protobuf enum <code>NULL_VALUE = 0;</code>
     */
    const NULL_VALUE = 0;
}

