<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.RecommendStorageRequest</code>
 */
class RecommendStorageRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Origin server of the request
     *
     * Generated from protobuf field <code>string originHostname = 1;</code>
     */
    private $originHostname = '';
    /**
     * Size of the file to place
     *
     * Generated from protobuf field <code>uint64 size = 2;</code>
     */
    private $size = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $originHostname
     *           Origin server of the request
     *     @type int|string $size
     *           Size of the file to place
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\File::initOnce();
        parent::__construct($data);
    }

    /**
     * Origin server of the request
     *
     * Generated from protobuf field <code>string originHostname = 1;</code>
     * @return string
     */
    public function getOriginHostname()
    {
        return $this->originHostname;
    }

    /**
     * Origin server of the request
     *
     * Generated from protobuf field <code>string originHostname = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOriginHostname($var)
    {
        GPBUtil::checkString($var, True);
        $this->originHostname = $var;

        return $this;
    }

    /**
     * Size of the file to place
     *
     * Generated from protobuf field <code>uint64 size = 2;</code>
     * @return int|string
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * Size of the file to place
     *
     * Generated from protobuf field <code>uint64 size = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkUint64($var);
        $this->size = $var;

        return $this;
    }

}

