<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.RecommendDownloadResponse</code>
 */
class RecommendDownloadResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pb.StatusCode status = 1;</code>
     */
    private $status = 0;
    /**
     * Generated from protobuf field <code>string origin = 2;</code>
     */
    private $origin = '';
    /**
     * Generated from protobuf field <code>string edge = 3;</code>
     */
    private $edge = '';
    /**
     * Generated from protobuf field <code>string path = 4;</code>
     */
    private $path = '';
    /**
     * We return information about the file for the proxy to do what ever it wants with
     *
     * Generated from protobuf field <code>.pb.FileType fileType = 5;</code>
     */
    private $fileType = 0;
    /**
     * Generated from protobuf field <code>.pb.Struct meta = 6;</code>
     */
    private $meta = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $status
     *     @type string $origin
     *     @type string $edge
     *     @type string $path
     *     @type int $fileType
     *           We return information about the file for the proxy to do what ever it wants with
     *     @type \Pb\Struct $meta
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\File::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pb.StatusCode status = 1;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.pb.StatusCode status = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Pb\StatusCode::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string origin = 2;</code>
     * @return string
     */
    public function getOrigin()
    {
        return $this->origin;
    }

    /**
     * Generated from protobuf field <code>string origin = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOrigin($var)
    {
        GPBUtil::checkString($var, True);
        $this->origin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string edge = 3;</code>
     * @return string
     */
    public function getEdge()
    {
        return $this->edge;
    }

    /**
     * Generated from protobuf field <code>string edge = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEdge($var)
    {
        GPBUtil::checkString($var, True);
        $this->edge = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string path = 4;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>string path = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * We return information about the file for the proxy to do what ever it wants with
     *
     * Generated from protobuf field <code>.pb.FileType fileType = 5;</code>
     * @return int
     */
    public function getFileType()
    {
        return $this->fileType;
    }

    /**
     * We return information about the file for the proxy to do what ever it wants with
     *
     * Generated from protobuf field <code>.pb.FileType fileType = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setFileType($var)
    {
        GPBUtil::checkEnum($var, \Pb\FileType::class);
        $this->fileType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pb.Struct meta = 6;</code>
     * @return \Pb\Struct
     */
    public function getMeta()
    {
        return $this->meta;
    }

    /**
     * Generated from protobuf field <code>.pb.Struct meta = 6;</code>
     * @param \Pb\Struct $var
     * @return $this
     */
    public function setMeta($var)
    {
        GPBUtil::checkMessage($var, \Pb\Struct::class);
        $this->meta = $var;

        return $this;
    }

}

