<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Pb;

/**
 * Protobuf type <code>pb.StatusCode</code>
 */
class StatusCode
{
    /**
     * Generated from protobuf enum <code>Ok = 0;</code>
     */
    const Ok = 0;
    /**
     * Generated from protobuf enum <code>InvalidUuid = 1;</code>
     */
    const InvalidUuid = 1;
    /**
     * Generated from protobuf enum <code>FileNotFound = 2;</code>
     */
    const FileNotFound = 2;
    /**
     * Generated from protobuf enum <code>FileAlreadyExists = 3;</code>
     */
    const FileAlreadyExists = 3;
    /**
     * Generated from protobuf enum <code>AlreadyPendingUpload = 5;</code>
     */
    const AlreadyPendingUpload = 5;
    /**
     * Generated from protobuf enum <code>AlreadyPendingDeletion = 4;</code>
     */
    const AlreadyPendingDeletion = 4;
    /**
     * Generated from protobuf enum <code>InternalServerErr = 500;</code>
     */
    const InternalServerErr = 500;
    /**
     * Generated from protobuf enum <code>NoServerAvailable = 520;</code>
     */
    const NoServerAvailable = 520;
}

