// Code generated by mockery v1.0.0. DO NOT EDIT.
package infinity_mocks

import context "context"

import mock "github.com/stretchr/testify/mock"

// ServerMetricCollector is an autogenerated mock type for the ServerMetricCollector type
type ServerMetricCollector struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx
func (_m *ServerMetricCollector) Run(ctx context.Context) {
	_m.Called(ctx)
}
