// Code generated by mockery v1.0.0. DO NOT EDIT.
package infinity_mocks

import minerva "git.misc.vee.bz/carnagel/minerva/pkg"
import mock "github.com/stretchr/testify/mock"

// ServerLoadBalanceStrategy is an autogenerated mock type for the ServerLoadBalanceStrategy type
type ServerLoadBalanceStrategy struct {
	mock.Mock
}

// Balance provides a mock function with given fields: keepServerAvailable, decide, determineServerBandWidth, filters
func (_m *ServerLoadBalanceStrategy) Balance(keepServerAvailable bool, decide minerva.LoadBalancerDecisionFunc, determineServerBandWidth minerva.ServerBandwidthFunc, filters []minerva.ServerFilterFunc) *minerva.Server {
	ret := _m.Called(keepServerAvailable, decide, determineServerBandWidth, filters)

	var r0 *minerva.Server
	if rf, ok := ret.Get(0).(func(bool, minerva.LoadBalancerDecisionFunc, minerva.ServerBandwidthFunc, []minerva.ServerFilterFunc) *minerva.Server); ok {
		r0 = rf(keepServerAvailable, decide, determineServerBandWidth, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*minerva.Server)
		}
	}

	return r0
}
