// Code generated by mockery v1.0.0. DO NOT EDIT.
package infinity_mocks

import context "context"

import mock "github.com/stretchr/testify/mock"

// ServerDiscovery is an autogenerated mock type for the ServerDiscovery type
type ServerDiscovery struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx
func (_m *ServerDiscovery) Run(ctx context.Context) {
	_m.Called(ctx)
}
