// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import common "git.misc.vee.bz/carnagel/go-ecosystem/protobuf/common"
import context "context"
import grpc "google.golang.org/grpc"
import mock "github.com/stretchr/testify/mock"

// BandwidthTrackingClient is an autogenerated mock type for the BandwidthTrackingClient type
type BandwidthTrackingClient struct {
	mock.Mock
}

// AddConsumedBandwidth provides a mock function with given fields: ctx, in, opts
func (_m *BandwidthTrackingClient) AddConsumedBandwidth(ctx context.Context, in *common.ConsumedBandwidthRequest, opts ...grpc.CallOption) (*common.RemainingBandwidthResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *common.RemainingBandwidthResponse
	if rf, ok := ret.Get(0).(func(context.Context, *common.ConsumedBandwidthRequest, ...grpc.CallOption) *common.RemainingBandwidthResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.RemainingBandwidthResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *common.ConsumedBandwidthRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRemainingBandwidth provides a mock function with given fields: ctx, in, opts
func (_m *BandwidthTrackingClient) GetRemainingBandwidth(ctx context.Context, in *common.Token, opts ...grpc.CallOption) (*common.RemainingBandwidthResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *common.RemainingBandwidthResponse
	if rf, ok := ret.Get(0).(func(context.Context, *common.Token, ...grpc.CallOption) *common.RemainingBandwidthResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.RemainingBandwidthResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *common.Token, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
