// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import ecosystem "git.misc.vee.bz/carnagel/go-ecosystem/domain"
import io "io"
import mock "github.com/stretchr/testify/mock"

// CamgirlGalleryClient is an autogenerated mock type for the CamgirlGalleryClient type
type CamgirlGalleryClient struct {
	mock.Mock
}

// Upload provides a mock function with given fields: name, data
func (_m *CamgirlGalleryClient) Upload(name string, data io.Reader) (*ecosystem.ImageUrls, error) {
	ret := _m.Called(name, data)

	var r0 *ecosystem.ImageUrls
	if rf, ok := ret.Get(0).(func(string, io.Reader) *ecosystem.ImageUrls); ok {
		r0 = rf(name, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ecosystem.ImageUrls)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, io.Reader) error); ok {
		r1 = rf(name, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
