// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import common "git.misc.vee.bz/carnagel/go-ecosystem/protobuf/common"
import context "context"
import mock "github.com/stretchr/testify/mock"

// DeviceTrackingServer is an autogenerated mock type for the DeviceTrackingServer type
type DeviceTrackingServer struct {
	mock.Mock
}

// DecDeviceCount provides a mock function with given fields: _a0, _a1
func (_m *DeviceTrackingServer) DecDeviceCount(_a0 context.Context, _a1 *common.Token) (*common.DecDeviceCountResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *common.DecDeviceCountResponse
	if rf, ok := ret.Get(0).(func(context.Context, *common.Token) *common.DecDeviceCountResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.DecDeviceCountResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *common.Token) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncDeviceCount provides a mock function with given fields: _a0, _a1
func (_m *DeviceTrackingServer) IncDeviceCount(_a0 context.Context, _a1 *common.Token) (*common.IncDeviceCountResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *common.IncDeviceCountResponse
	if rf, ok := ret.Get(0).(func(context.Context, *common.Token) *common.IncDeviceCountResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.IncDeviceCountResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *common.Token) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
