// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import common "git.misc.vee.bz/carnagel/go-ecosystem/protobuf/common"
import context "context"
import grpc "google.golang.org/grpc"
import mock "github.com/stretchr/testify/mock"

// DeviceTrackingClient is an autogenerated mock type for the DeviceTrackingClient type
type DeviceTrackingClient struct {
	mock.Mock
}

// DecDeviceCount provides a mock function with given fields: ctx, in, opts
func (_m *DeviceTrackingClient) DecDeviceCount(ctx context.Context, in *common.Token, opts ...grpc.CallOption) (*common.DecDeviceCountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *common.DecDeviceCountResponse
	if rf, ok := ret.Get(0).(func(context.Context, *common.Token, ...grpc.CallOption) *common.DecDeviceCountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.DecDeviceCountResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *common.Token, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncDeviceCount provides a mock function with given fields: ctx, in, opts
func (_m *DeviceTrackingClient) IncDeviceCount(ctx context.Context, in *common.Token, opts ...grpc.CallOption) (*common.IncDeviceCountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *common.IncDeviceCountResponse
	if rf, ok := ret.Get(0).(func(context.Context, *common.Token, ...grpc.CallOption) *common.IncDeviceCountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.IncDeviceCountResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *common.Token, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
