- name: add repositroy for raid tools
  become: yes
  apt_repository:
    repo: "deb http://hwraid.le-vert.net/ubuntu xenial main"
    state: present

- name: add key for raid repositroy
  become: yes
  apt_key:
    url: http://hwraid.le-vert.net/debian/hwraid.le-vert.net.gpg.key
    state: present

- name: update apt
  become: yes
  apt:
    update_cache: yes

- name: install raid tools
  become: yes
  apt:
    name: "{{ item }}"
    allow_unauthenticated: yes
    state: latest
  with_items:
    - megacli
    - megactl
    - megaraid-status
    - smartmontools
