- name: Install bitcoin conf
  template:
    src: bitcoin.conf
    dest: /etc/bitcoin/bitcoin.conf
  become: yes

- name: Upload btc-node template
  template:
    src: btc-node.nomad
    dest: ./btc-node.nomad
  delegate_to: "{{ item }}"
  delegate_facts: yes
  with_items: "{{ groups['masters'] }}"
  run_once: yes

- name: Tell nomad to run the updated job
  command: nomad run btc-node.nomad
  delegate_to: "{{ item }}"
  delegate_facts: yes
  with_items: "{{ groups['masters'] }}"
  run_once: yes