- name: Upload btc-wallet template
  template:
    src: btc-wallet.nomad
    dest: ./btc-wallet.nomad
  delegate_to: "{{ item }}"
  delegate_facts: yes
  with_items: "{{ groups['masters'] }}"
  run_once: yes

- name: Tell nomad to run the updated job
  command: nomad run btc-wallet.nomad
  delegate_to: "{{ item }}"
  delegate_facts: yes
  with_items: "{{ groups['masters'] }}"
  run_once: yes