// Code generated by mockery v1.0.0. DO NOT EDIT.

package infinity_mocks

import infinity "git.misc.vee.bz/carnagel/infinity-api/pkg"
import mock "github.com/stretchr/testify/mock"

// EmailService is an autogenerated mock type for the EmailService type
type EmailService struct {
	mock.Mock
}

// SendAccountCancellationEmail provides a mock function with given fields: _a0
func (_m *EmailService) SendAccountCancellationEmail(_a0 *infinity.User) {
	_m.Called(_a0)
}

// SendAccountCreationEmail provides a mock function with given fields: _a0
func (_m *EmailService) SendAccountCreationEmail(_a0 *infinity.User) {
	_m.Called(_a0)
}

// SendEmailFromTemplateFile provides a mock function with given fields: _a0, _a1, _a2
func (_m *EmailService) SendEmailFromTemplateFile(_a0 string, _a1 string, _a2 string) {
	_m.Called(_a0, _a1, _a2)
}

// SendPasswordResetEmail provides a mock function with given fields: _a0, _a1
func (_m *EmailService) SendPasswordResetEmail(_a0 *infinity.User, _a1 string) {
	_m.Called(_a0, _a1)
}

// SendPaymentPlanExpiredEmail provides a mock function with given fields: _a0
func (_m *EmailService) SendPaymentPlanExpiredEmail(_a0 *infinity.User) {
	_m.Called(_a0)
}

// SendPaymentPlanExpiryReminderEmail provides a mock function with given fields: _a0, _a1
func (_m *EmailService) SendPaymentPlanExpiryReminderEmail(_a0 *infinity.User, _a1 uint) {
	_m.Called(_a0, _a1)
}

// SendPurchasedRegularPremiumEmail provides a mock function with given fields: _a0, _a1, _a2
func (_m *EmailService) SendPurchasedRegularPremiumEmail(_a0 *infinity.User, _a1 *infinity.PaymentPlan, _a2 *infinity.PaymentTransaction) {
	_m.Called(_a0, _a1, _a2)
}

// SendPurchasedTierTwoPremiumEmail provides a mock function with given fields: _a0
func (_m *EmailService) SendPurchasedTierTwoPremiumEmail(_a0 *infinity.User) {
	_m.Called(_a0)
}
