// Code generated by mockery v1.0.0. DO NOT EDIT.

package infinity_mocks

import ecosystem "git.misc.vee.bz/carnagel/go-ecosystem/domain"
import infinity "git.misc.vee.bz/carnagel/infinity-api/pkg"
import mock "github.com/stretchr/testify/mock"

// PerformerService is an autogenerated mock type for the PerformerService type
type PerformerService struct {
	mock.Mock
}

// ImportFromAphrodite provides a mock function with given fields: performer
func (_m *PerformerService) ImportFromAphrodite(performer *ecosystem.Performer) (*infinity.Performer, error) {
	ret := _m.Called(performer)

	var r0 *infinity.Performer
	if rf, ok := ret.Get(0).(func(*ecosystem.Performer) *infinity.Performer); ok {
		r0 = rf(performer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*infinity.Performer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*ecosystem.Performer) error); ok {
		r1 = rf(performer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
