// Code generated by mockery v1.0.0. DO NOT EDIT.

package infinity_mocks

import mock "github.com/stretchr/testify/mock"
import rpc "git.misc.vee.bz/carnagel/infinity-api/pkg/infrastructure/http/rpc"

// RequestServer is an autogenerated mock type for the RequestServer type
type RequestServer struct {
	mock.Mock
}

// ServeRequest provides a mock function with given fields: _a0, _a1
func (_m *RequestServer) ServeRequest(_a0 rpc.Socket, _a1 *rpc.Request) {
	_m.Called(_a0, _a1)
}
