// Code generated by mockery v1.0.0. DO NOT EDIT.

package infinity_mocks

import mock "github.com/stretchr/testify/mock"

// Socket is an autogenerated mock type for the Socket type
type Socket struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Socket) Close() {
	_m.Called()
}

// Send provides a mock function with given fields: _a0
func (_m *Socket) Send(_a0 []byte) {
	_m.Called(_a0)
}

// SetValue provides a mock function with given fields: _a0, _a1
func (_m *Socket) SetValue(_a0 string, _a1 interface{}) {
	_m.Called(_a0, _a1)
}

// Value provides a mock function with given fields: _a0
func (_m *Socket) Value(_a0 string) interface{} {
	ret := _m.Called(_a0)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}
