// Code generated by mockery v1.0.0. DO NOT EDIT.
package coordinator_mocks

import ecosystem "git.misc.vee.bz/carnagel/go-ecosystem/domain"
import mock "github.com/stretchr/testify/mock"

// ContentService is an autogenerated mock type for the ContentService type
type ContentService struct {
	mock.Mock
}

// Publish provides a mock function with given fields: recording
func (_m *ContentService) Publish(recording *ecosystem.Recording) error {
	ret := _m.Called(recording)

	var r0 error
	if rf, ok := ret.Get(0).(func(*ecosystem.Recording) error); ok {
		r0 = rf(recording)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RebuildUltron provides a mock function with given fields: lastSeenId
func (_m *ContentService) RebuildUltron(lastSeenId uint64) error {
	ret := _m.Called(lastSeenId)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(lastSeenId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Remove provides a mock function with given fields: recording, system
func (_m *ContentService) Remove(recording *ecosystem.Recording, system string) error {
	ret := _m.Called(recording, system)

	var r0 error
	if rf, ok := ret.Get(0).(func(*ecosystem.Recording, string) error); ok {
		r0 = rf(recording, system)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
