// Code generated by mockery v1.0.0. DO NOT EDIT.
package coordinator_mocks

import context "context"

import mock "github.com/stretchr/testify/mock"

// RecordingRepository is an autogenerated mock type for the RecordingRepository type
type RecordingRepository struct {
	mock.Mock
}

// GetPublishedRecordingIds provides a mock function with given fields: ctx, lastSeenId
func (_m *RecordingRepository) GetPublishedRecordingIds(ctx context.Context, lastSeenId uint64) (<-chan uint64, error) {
	ret := _m.Called(ctx, lastSeenId)

	var r0 <-chan uint64
	if rf, ok := ret.Get(0).(func(context.Context, uint64) <-chan uint64); ok {
		r0 = rf(ctx, lastSeenId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan uint64)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, lastSeenId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
