// Code generated by mockery v1.0.0. DO NOT EDIT.
package coordinator_mocks

import context "context"

import http "net/http"
import mock "github.com/stretchr/testify/mock"
import url "net/url"

// ScraperProxyService is an autogenerated mock type for the ScraperProxyService type
type ScraperProxyService struct {
	mock.Mock
}

// GetProxy provides a mock function with given fields: r
func (_m *ScraperProxyService) GetProxy(r *http.Request) (*url.URL, error) {
	ret := _m.Called(r)

	var r0 *url.URL
	if rf, ok := ret.Get(0).(func(*http.Request) *url.URL); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.URL)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Run provides a mock function with given fields: ctx
func (_m *ScraperProxyService) Run(ctx context.Context) {
	_m.Called(ctx)
}
