# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import minerva.struct_pb2 as struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='pb',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x63ommon.proto\x12\x02pb\x1a\x0cstruct.proto\"\xa7\x02\n\x08\x46ileData\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x12\n\nexternalId\x18\x02 \x01(\x04\x12\x1a\n\x04type\x18\x03 \x01(\x0e\x32\x0c.pb.FileType\x12\x10\n\x08hostname\x18\x04 \x01(\t\x12\x0c\n\x04path\x18\x05 \x01(\t\x12\x13\n\x0bupstoreHash\x18\x06 \x01(\t\x12\x18\n\x10originalFilename\x18\x07 \x01(\t\x12\x10\n\x08\x63hecksum\x18\x0e \x01(\t\x12\x15\n\rpendingUpload\x18\x08 \x01(\x08\x12\x17\n\x0fpendingDeletion\x18\t \x01(\x08\x12\x0c\n\x04size\x18\n \x01(\x04\x12\x18\n\x04meta\x18\x0b \x01(\x0b\x32\n.pb.Struct\x12\x11\n\tcreatedAt\x18\x0c \x01(\t\x12\x11\n\tupdatedAt\x18\r \x01(\t*\xb4\x01\n\nStatusCode\x12\x06\n\x02Ok\x10\x00\x12\x0f\n\x0bInvalidUuid\x10\x01\x12\x10\n\x0c\x46ileNotFound\x10\x02\x12\x15\n\x11\x46ileAlreadyExists\x10\x03\x12\x18\n\x14\x41lreadyPendingUpload\x10\x05\x12\x1a\n\x16\x41lreadyPendingDeletion\x10\x04\x12\x16\n\x11InternalServerErr\x10\xf4\x03\x12\x16\n\x11NoServerAvailable\x10\x88\x04*\x8f\x01\n\x08\x46ileType\x12\x07\n\x03\x41ll\x10\x00\x12\x11\n\rRecording_mp4\x10\x01\x12\x11\n\rRecording_hls\x10\x06\x12\x15\n\x11Wordpress_collage\x10\x02\x12\x14\n\x10Infinity_collage\x10\x03\x12\x13\n\x0fInfinity_sprite\x10\x04\x12\x12\n\x0eInfinity_image\x10\x05\x62\x06proto3')
  ,
  dependencies=[struct__pb2.DESCRIPTOR,])

_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='pb.StatusCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Ok', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='InvalidUuid', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FileNotFound', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FileAlreadyExists', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AlreadyPendingUpload', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AlreadyPendingDeletion', index=5, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='InternalServerErr', index=6, number=500,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NoServerAvailable', index=7, number=520,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=333,
  serialized_end=513,
)
_sym_db.RegisterEnumDescriptor(_STATUSCODE)

StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
_FILETYPE = _descriptor.EnumDescriptor(
  name='FileType',
  full_name='pb.FileType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='All', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Recording_mp4', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Recording_hls', index=2, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Wordpress_collage', index=3, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Infinity_collage', index=4, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Infinity_sprite', index=5, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Infinity_image', index=6, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=516,
  serialized_end=659,
)
_sym_db.RegisterEnumDescriptor(_FILETYPE)

FileType = enum_type_wrapper.EnumTypeWrapper(_FILETYPE)
Ok = 0
InvalidUuid = 1
FileNotFound = 2
FileAlreadyExists = 3
AlreadyPendingUpload = 5
AlreadyPendingDeletion = 4
InternalServerErr = 500
NoServerAvailable = 520
All = 0
Recording_mp4 = 1
Recording_hls = 6
Wordpress_collage = 2
Infinity_collage = 3
Infinity_sprite = 4
Infinity_image = 5



_FILEDATA = _descriptor.Descriptor(
  name='FileData',
  full_name='pb.FileData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='pb.FileData.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='externalId', full_name='pb.FileData.externalId', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='pb.FileData.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hostname', full_name='pb.FileData.hostname', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='pb.FileData.path', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='upstoreHash', full_name='pb.FileData.upstoreHash', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='originalFilename', full_name='pb.FileData.originalFilename', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='checksum', full_name='pb.FileData.checksum', index=7,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pendingUpload', full_name='pb.FileData.pendingUpload', index=8,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pendingDeletion', full_name='pb.FileData.pendingDeletion', index=9,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='pb.FileData.size', index=10,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='meta', full_name='pb.FileData.meta', index=11,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='createdAt', full_name='pb.FileData.createdAt', index=12,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='updatedAt', full_name='pb.FileData.updatedAt', index=13,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=330,
)

_FILEDATA.fields_by_name['type'].enum_type = _FILETYPE
_FILEDATA.fields_by_name['meta'].message_type = struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['FileData'] = _FILEDATA
DESCRIPTOR.enum_types_by_name['StatusCode'] = _STATUSCODE
DESCRIPTOR.enum_types_by_name['FileType'] = _FILETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileData = _reflection.GeneratedProtocolMessageType('FileData', (_message.Message,), dict(
  DESCRIPTOR = _FILEDATA,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:pb.FileData)
  ))
_sym_db.RegisterMessage(FileData)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
