# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import minerva.file_pb2 as file__pb2


class FileStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Get = channel.unary_unary(
        '/pb.File/Get',
        request_serializer=file__pb2.GetRequest.SerializeToString,
        response_deserializer=file__pb2.GetResponse.FromString,
        )
    self.Create = channel.unary_unary(
        '/pb.File/Create',
        request_serializer=file__pb2.CreateRequest.SerializeToString,
        response_deserializer=file__pb2.CreateResponse.FromString,
        )
    self.Update = channel.unary_unary(
        '/pb.File/Update',
        request_serializer=file__pb2.UpdateRequest.SerializeToString,
        response_deserializer=file__pb2.UpdateResponse.FromString,
        )
    self.RequestDeletion = channel.unary_unary(
        '/pb.File/RequestDeletion',
        request_serializer=file__pb2.DeleteRequest.SerializeToString,
        response_deserializer=file__pb2.DeleteResponse.FromString,
        )
    self.RequestUpload = channel.unary_unary(
        '/pb.File/RequestUpload',
        request_serializer=file__pb2.UploadRequest.SerializeToString,
        response_deserializer=file__pb2.UploadResponse.FromString,
        )


class FileServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Get(self, request, context):
    """CRUD tasks
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Update(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RequestDeletion(self, request, context):
    """This does not happen instantily, it requires the minion delegation system to dispatch and verify the delete
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RequestUpload(self, request, context):
    """Upload a specific file
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FileServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=file__pb2.GetRequest.FromString,
          response_serializer=file__pb2.GetResponse.SerializeToString,
      ),
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=file__pb2.CreateRequest.FromString,
          response_serializer=file__pb2.CreateResponse.SerializeToString,
      ),
      'Update': grpc.unary_unary_rpc_method_handler(
          servicer.Update,
          request_deserializer=file__pb2.UpdateRequest.FromString,
          response_serializer=file__pb2.UpdateResponse.SerializeToString,
      ),
      'RequestDeletion': grpc.unary_unary_rpc_method_handler(
          servicer.RequestDeletion,
          request_deserializer=file__pb2.DeleteRequest.FromString,
          response_serializer=file__pb2.DeleteResponse.SerializeToString,
      ),
      'RequestUpload': grpc.unary_unary_rpc_method_handler(
          servicer.RequestUpload,
          request_deserializer=file__pb2.UploadRequest.FromString,
          response_serializer=file__pb2.UploadResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pb.File', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class LoadBalancerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RecommendStorage = channel.unary_unary(
        '/pb.LoadBalancer/RecommendStorage',
        request_serializer=file__pb2.RecommendStorageRequest.SerializeToString,
        response_deserializer=file__pb2.RecommendStorageResponse.FromString,
        )
    self.RecommendDownload = channel.unary_unary(
        '/pb.LoadBalancer/RecommendDownload',
        request_serializer=file__pb2.RecommendDownloadRequest.SerializeToString,
        response_deserializer=file__pb2.RecommendDownloadResponse.FromString,
        )


class LoadBalancerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RecommendStorage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RecommendDownload(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LoadBalancerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RecommendStorage': grpc.unary_unary_rpc_method_handler(
          servicer.RecommendStorage,
          request_deserializer=file__pb2.RecommendStorageRequest.FromString,
          response_serializer=file__pb2.RecommendStorageResponse.SerializeToString,
      ),
      'RecommendDownload': grpc.unary_unary_rpc_method_handler(
          servicer.RecommendDownload,
          request_deserializer=file__pb2.RecommendDownloadRequest.FromString,
          response_serializer=file__pb2.RecommendDownloadResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pb.LoadBalancer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
