<?php

return [
    'ultron' => [
       'sites' => [
            [
                'enabled' => true,
                'urlRoot' => 'cam-models-videos',
                'domain'  => 'camvideos.me',
                'service' => null,
                'section' => null,
                'theme'   => '/css/camvideos.css',
                'favicon' => '/img/camvideos/favicon.png',
            ],
            [
                'enabled' => true,
                'urlRoot' => 'myfreecams-videos',
                'domain'  => 'teencamvideos.me',
                'service' => 'mfc',
                'section' => null,
                'theme'   => '/css/teencamvideos.css',
                'favicon' => '/img/teencamvideos/favicon.png',
            ],
            [
                'enabled' => true,
                'urlRoot' => 'chaturbate-boy-videos',
                'domain'  => 'boycams.me',
                'service' => 'cbc',
                'section' => 'male',
                'theme'   => '/css/boycamvideos.css',
                'favicon' => '/img/boycamvideos/favicon.png',
            ],
            [
                'enabled' => true,
                'urlRoot' => 'chaturbate-girl-videos',
                'domain'  => 'nakedcamvideos.me',
                'service' => 'cbc',
                'section' => 'female',
                'theme'   => '/css/nakedcamvideos.css',
                'favicon' => '/img/nakedcamvideos/favicon.png',
            ],
            [
                'enabled' => true,
                'urlRoot' => 'chaturbate-sex-videos',
                'domain'  => 'hardcorecams.me',
                'service' => 'cbc',
                'section' => 'couple',
                'theme'   => '/css/hardcorecams.css',
                'favicon' => '/img/hardcorecams/favicon.png',
            ],

            [
                'enabled' => true,
                'urlRoot' => 'all-models-videos',
                'domain'  => 'camcaps.me',
                'service' => null,
                'section' => null,
                'theme'   => '/css/camcaps.css',
                'favicon' => '/img/camcaps/favicon.png',
            ],
            [
                'enabled' => true,
                'urlRoot' => 'myfreecams-models-videos',
                'domain'  => 'sweetcams.me',
                'service' => 'mfc',
                'section' => null,
                'theme'   => '/css/sweetcams.css',
                'favicon' => '/img/sweetcams/favicon.png',
            ],
            [
                'enabled' => true,
                'urlRoot' => 'chaturbate-male-videos',
                'domain'  => 'malecams.me',
                'service' => 'cbc',
                'section' => 'male',
                'theme'   => '/css/malecams.css',
                'favicon' => '/img/malecams/favicon.png',
            ],
            [
                'enabled' => true,
                'urlRoot' => 'chaturbate-female-videos',
                'domain'  => 'nakedcams.me',
                'service' => 'cbc',
                'section' => 'female',
                'theme'   => '/css/nakedcams.css',
                'favicon' => 'img/nakedcams/favicon.png',
            ],
            [
                'enabled' => true,
                'urlRoot' => 'chaturbate-couples-videos',
                'domain'  => 'camsexvideos.me',
                'service' => 'cbc',
                'section' => 'couple',
                'theme'   => '/css/camsexvideos.css',
                'favicon' => '/img/camsexvideos/favicon.png',
            ],

            // DON'T TOUCH BELLOW THIS UNLESS YOU KNOW WHAT YOU ARE DOING
            [
                'enabled' => false,
                'urlRoot' => 'dev',
                'domain'  => 'ultron.dev',
                'service' => null,
                'section' => null,
                'theme'   => '/css/teencamvideos.css',
                'favicon' => '/img/teencamvideos/favicon.png',
            ],
        ],
    ],
];
