// Code generated by mockery v1.0.0
package mocks

import context "context"

import mock "github.com/stretchr/testify/mock"

// ExecutionerService is an autogenerated mock type for the ExecutionerService type
type ExecutionerService struct {
	mock.Mock
}

// ProcessDeletions provides a mock function with given fields: ctx
func (_m *ExecutionerService) ProcessDeletions(ctx context.Context) {
	_m.Called(ctx)
}

// ProcessRelocationRequests provides a mock function with given fields: ctx
func (_m *ExecutionerService) ProcessRelocationRequests(ctx context.Context) {
	_m.Called(ctx)
}

// ProcessUploads provides a mock function with given fields: ctx
func (_m *ExecutionerService) ProcessUploads(ctx context.Context) {
	_m.Called(ctx)
}
