// Code generated by mockery v1.0.0
package mocks

import context "context"
import minion "git.misc.vee.bz/carnagel/minion/pkg"
import mock "github.com/stretchr/testify/mock"

// FilesystemIntegrity is an autogenerated mock type for the FilesystemIntegrity type
type FilesystemIntegrity struct {
	mock.Mock
}

// GetReport provides a mock function with given fields:
func (_m *FilesystemIntegrity) GetReport() minion.IntegrityReport {
	ret := _m.Called()

	var r0 minion.IntegrityReport
	if rf, ok := ret.Get(0).(func() minion.IntegrityReport); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(minion.IntegrityReport)
	}

	return r0
}

// IsRunning provides a mock function with given fields:
func (_m *FilesystemIntegrity) IsRunning() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Run provides a mock function with given fields: ctx
func (_m *FilesystemIntegrity) Run(ctx context.Context) {
	_m.Called(ctx)
}
