- name: Deploy central microservices
  hosts: masters
  roles:
    - central

  pre_tasks:
    - name: check required variables
      fail: msg="build_number is not defined"
      when: build_number is not defined