---
- name: Deploy hermes
  hosts: php
  roles:
    - role: 'nginx'
      tags: ['nginx']
      become: yes,
      when: nginx_master == 'yes'

    - role: 'php-fpm'
      tags: ['php-fpm']
      become: yes

    - role: 'hermes'
      tags: ['hermes']

  vars_files:
    - app_vars/hermes.yml