# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu_1404_amd64"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  # Network
  config.vm.network "private_network", ip: "192.168.10.101"
  config.vm.hostname = "download-dev"
  config.ssh.forward_agent = true

  # Synced folders
  config.vm.synced_folder ".", "/opt/application", nfs: true
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "4"]
  end

  config.vm.provision :ansible do |ansible|
    ansible.limit          = "development"
    ansible.playbook       = "provisioning/development.yml"
    ansible.inventory_path = "provisioning/ansible-hosts"
  end

  if Vagrant.has_plugin?("vagrant-cachier")
      config.cache.scope = :box
      config.cache.synced_folder_opts = {
        type: :nfs,
        mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
      }
  end
end
