version: '3'
services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: 'infinity'
      POSTGRES_PASSWORD: 'infinity'
      POSTGRES_DATABASE: 'infinity'
      SERVICE_5432_NAME: 'postgres'

    ports:
      - 5432:5432

    command: postgres -c log_statement=all -c logging_collector=on -c log_destination=stderr

    depends_on:
      - registrator
      - consul

  redis:
    image: redis:latest
    ports:
      - 6379:6379

    environment:
      SERVICE_6379_NAME: 'redis'

  elasticsearch:
    image: elasticsearch:5.2
    ports:
      - 9200:9200

    depends_on:
      - registrator
      - consul

    environment:
      SERVICE_9200_NAME: 'elasticsearch'

  consul:
    image: consul:latest
    ports:
      - 8500:8500
    environment:
      SERVICE_8500_NAME: 'consul'

  registrator:
    image: gliderlabs/registrator:latest
    network_mode: host
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

    command: consul://localhost:8500
    depends_on:
      - consul
