# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[[constraint]]
  name = "github.com/gosimple/slug"
  version = "v1.1.0"

[[constraint]]
  name = "git.misc.vee.bz/carnagel/sql-migrations"
  source =  "git@git.misc.vee.bz:carnagel/sql-migrations.git"
  version = "^0.0.2"

[[constraint]]
  name = "github.com/blockcypher/gobcy"
  version = "1.3.1"

[[constraint]]
  name = "gopkg.in/gomail.v2"
  version = "^2.0.0"

[[constraint]]
  name = "github.com/go-pg/pg"
  revision = "a03636c3c61892362844db10b3e931edfb0b8fc3"

[[constraint]]
  name = "github.com/gorilla/handlers"
  revision = "90663712d74cb411cbef281bc1e08c19d1a76145"

[[constraint]]
  name = "git.misc.vee.bz/carnagel/go-ecosystem"
  source = "git@git.misc.vee.bz:carnagel/go-ecosystem.git"
  version = "0.3.5"

[[constraint]]
  name = "github.com/sasha-s/go-deadlock"
  version = "v0.2.0"

[prune]
  go-tests = true
  unused-packages = true
